### ISSUE TITLE
why are you guys not allowing root as my password ? why this restriction suddenly ? UPDATE mysql.user SET authentication_string=password('root') where User='root';

### ISSUE THREAD

**Issue by bismoy2013** [ShahriyarR/MySQL-AutoXtraBackup#10]
mysql> UPDATE mysql.user SET authentication_string=password('1111') where User='root';
ERROR 1819 (HY000): Your password does not satisfy the current policy requirements

**Comment by ShahriyarR** [comment]
Hi,
Could you please share more info? exactly where you got this error?

**Comment by bismoy2013** [comment]
For people who might refer this thread in future : 

mysql> SET GLOBAL validate_password_length = 4;
Query OK, 0 rows affected (0.01 sec)

mysql> SHOW VARIABLES LIKE 'validate_password%';
+--------------------------------------+--------+
| Variable_name                        | Value  |
+--------------------------------------+--------+
| validate_password_dictionary_file    |        |
| validate_password_length             | 4      |
| validate_password_mixed_case_count   | 1      |
| validate_password_number_count       | 1      |
| validate_password_policy             | MEDIUM |
| validate_password_special_char_count | 1      |
+--------------------------------------+--------+
6 rows in set (0.00 sec)

mysql> SET GLOBAL validate_password_policy = LOW;
Query OK, 0 rows affected (0.01 sec)

**Comment by ShahriyarR** [comment]
Password Validation Plugin is part of MySQL. I did not know how it was affected by this project.
See documentation:
[Validate Password Plugin](https://dev.mysql.com/doc/refman/5.6/en/validate-password-plugin.html)

You can even completely uninstall plugin or change password policy etc.:

[validate-password-options-variables](https://dev.mysql.com/doc/refman/5.6/en/validate-password-options-variables.html)

Thanks.

**Comment by bismoy2013** [comment]
I was just trying normal password "root" , didn't realize even for that I need to set and change the existing password rules , never had to do these steps but looks like mysql has introduced some changes recently!

**Comment by ShahriyarR** [comment]
Yeap you are right :)
Password Validation and many more new features available since 5.6 version.
