### ISSUE TITLE
Partial recovery version detection bug

### ISSUE THREAD

**Issue by JasperAlgra** [ShahriyarR/MySQL-AutoXtraBackup#116]
Hi, 
When trying to do a partial restore the version check fails, even though I've got mysql-server 5.6.33. 

After some debugging I've found the bug on partial.py:92:

I've added 
`logger.debug("MySQL Version is, %s" % output[-13:])`, which outputs: 
`MySQL Version is, 6.33-79.0-log`

`select @@version;` in mysql console gives: `5.6.33-79.0-log`. So the -minus 13 is not long enough.

As I'm totally not a python programmer and I can't see the reason for a right side- cut instead of left I won't attempt to make a pull request.

**Comment by ShahriyarR** [comment]
Hi and thanks checking out.
After your report, I am curious about, why historically I have added this output[-13:] here at all :)
Trying to figure out.

**Comment by ShahriyarR** [comment]
@JasperAlgra yeah, I have figured out what was the purpose of this syntax here.
So basically after running mysql client command the output is something like:

```
import subprocess

cmd = '/home/shahriyar.rzaev/XB_TEST/server_dir/PS161017-percona-server-5.6.37-82.2-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS161017-percona-server-5.6.37-82.2-linux-x86_64-debug/socket.sock -e "select @@version"'

status, output = subprocess.getstatusoutput(cmd)

print(output)
```

```
$ python python_test.py
@@version
5.6.37-82.2-debug
```
The @@version column also represented in output. That's I have tried to cut only version portion but hardcoded it in a wrong way.

So could you please change your code and test it again?

```
    def check_mysql_version(self):
        """
        Function for checking MySQL version.
        Version must be >= 5.6 for using "Transportable Tablespace" concept.
        :return: True/False
        """
        statement = "select @@version"
        run_command = self.create_mysql_client_command(statement=statement)

        logger.debug("Checking MySQL version")
        status, output = subprocess.getstatusoutput(run_command)

        if status == 0 and ('5.6' in output):
            logger.debug("You have correct version of MySQL")
            return True
        elif status == 0 and ('5.7' in output):
            logger.debug("You have correct version of MySQL")
            return True
        elif status == 0 and ('5.7' not in output) and ('5.6' not in output):
            logger.error("Your MySQL server is not supported")
            logger.error("MySQL version must be >= 5.6")
            return False
        else:
            logger.error("Check FAILED!")
            logger.error(output)
            return False
```

**Comment by JasperAlgra** [comment]
Hi @ShahriyarR . Thanks for looking at this issue so quick.
Just tested it and your fix works good. Did a quickfix by changing the -13 to -15 but this is better.

I have another small issue, due to the 'install_require mysql-connector >2.0.2'  in setup.py on debian installation but maybe it's better to open a seperate issue for this?

**Comment by ShahriyarR** [comment]
Please open a new one for this installation issue.

**Comment by ShahriyarR** [comment]
@JasperAlgra please send a PR for this issue, I will merge it in the next release.
Thanks.

**Comment by ShahriyarR** [comment]
Merged to release_v1.4.9 branch and will be released as GA soon.

**Comment by JasperAlgra** [comment]
Hi @ShahriyarR sorry, I was very busy last week so didn't came around to send in the pull request. I only had a total merge of this and the other issue I've raised. 
Thanks again for fixing this!

**Comment by ShahriyarR** [comment]
@JasperAlgra No worries at all :)
Please keep testing this project and log a lot of bugs to improve it.
Thanks.
