### ISSUE TITLE
Installation dependency issue on Debian and windows

### ISSUE THREAD

**Issue by JasperAlgra** [ShahriyarR/MySQL-AutoXtraBackup#117]
Hi,

The 
``` 
install_requires=[
        'mysql-connector>=2.0.2',
]
``` 
which can be found on setup.py:18. Creates an issue on when installing on debian or windows.

Result: `Unable to find Protobuf include directory.`

On debian (8) this can be fixed by installing manually: 
* `wget https://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python-py3_2.1.7-1debian8.2_all.deb`
* `dpkg -i mysql-connector-python-py3_2.1.7-1debian8.2_all.deb`

and commenting out the dependency `sed -i '/mysql-connector>/s/^/#/' setup.py`

On windows the dependency issue is exactly the same, but I'm still working on a fix. The mysql-connector package won't play nice (install) when not using the .msi installer for python3.

**Comment by ShahriyarR** [comment]
Hi,
Ah right, this is the same issue here as I have reported to MySQL previously:

https://bugs.mysql.com/bug.php?id=85666

The workaround is to change and use exact version 2.1.4 here:

```
install_requires=[
        'mysql-connector==2.1.4',
]
```

So could you please test it also?
I have already fixed it in release 1.4.9 but not yet released(it is in draft).

**Comment by JasperAlgra** [comment]
Tested both on Windows (10) and Debian 8, both python 3.4 and works both. Thanks!

Funny because pip install on debian of python-mysql-connector 2.1.4 failed as well.  `pip install mysql-connector==2.1.4`

Thanks once again :)

**Comment by ShahriyarR** [comment]
:) It is a pleasure.
Thank you for testing.
Please do not hesitate to open new issues and contact me directly.
