### ISSUE TITLE
define mysql ipaddress config with bind-address [my.cnf]

### ISSUE THREAD

**Issue by raminfp** [ShahriyarR/MySQL-AutoXtraBackup#14]
Hi,

Thanks for repo, i think you should define variable for remote ipaddress with bind-address in my.cnf config file , now this is a static `'127.0.0.1'`, 

https://github.com/ShahriyarR/MySQL-AutoXtraBackup/blob/master/master_backup_script/backuper.py#L106

**Comment by ShahriyarR** [comment]
Hi, 
Keeping in mind that, this tool should be used only in local machine, as it is requirement for Percona XtraBackup. 

Specified code is in mysql_connection_flush_logs() -> function, which is going to run "flush logs" command in local MySQL server.  

And the line you have specified will be changed as soon as the dedicated PR will be merged into main repo, to support socket connection.
the PR:

https://github.com/ShahriyarR/MySQL-AutoXtraBackup/pull/13

The commit:

https://github.com/ShahriyarR/MySQL-AutoXtraBackup/pull/13/commits/03c59dba086564e95725842ff42e9bafd1bdf76d

**Comment by ShahriyarR** [comment]
Now it is merged. Closing.

**Comment by raminfp** [comment]
Thanks, Yes, Merged! https://github.com/ShahriyarR/MySQL-AutoXtraBackup/commit/34dad6d12e693e59dfbe0912bc57689a5f7aa970

**Comment by ShahriyarR** [comment]
@raminfp I am going to improve tool, to use `xtrabackup` instead of `innobackupex`
Further changes will be shown here -> https://github.com/ShahriyarR/MySQL-AutoXtraBackup/issues/15
Please keep updated and thanks for interest :)
