### ISSUE TITLE
Feature Request - Can we TAG our backups?

### ISSUE THREAD

**Issue by Komport** [ShahriyarR/MySQL-AutoXtraBackup#163]
Is it possible to add optional feature to TAG our backups. Say if I have 10 inc backups, each taken after some specific action, so  It will be very handy if i can add tag to each of them or some of them (critical ones).
Like below
```
[root@server1 MySQL-AutoXtraBackup]# autoxtrabackup --backup --TAG "Before Testdb - test table - test column drop"
```

**Comment by ShahriyarR** [comment]
Hi, it is possible of course.
But how this tag will be stored?

**Comment by Komport** [comment]
For example you can keep as txt file in each backupdir.

**Comment by ShahriyarR** [comment]
Or we can keep 1 file inside backup_dir named as `backup_tags.txt` and append there each time we are doing the backup.

**Comment by ShahriyarR** [comment]
So I am going to implement this in with following steps:
* The new `--tag` option can be added to add new entries for each backup.
* `--show_tags` options can be added to show those tags.
* `--show_tags` must be used only with --defaults_file to get the backup_dir path and other things from config.
* `--show_tags` should raise an exception if backup_tags.txt missing from backup_dir.

Please feel free to add some more things here.

**Comment by Komport** [comment]
With one file it will be more job to do i think. What I feel is to place in each folder txt file with its tag. And it should be optional. Users do not like exceptions in tools, especially DB admins, especially in backup and restore tools :)

**Comment by ShahriyarR** [comment]
:) Well, thats means you have not used --tag option before and now you want to show tags?

Let's describe a situation where you have 1 full + 12 incremental backups:
* For storing tags in each folder we need 13 backup_tags.txt + each time for showing tags we should recursively go through all backup folders open those files, reading appending to empty list then show in the output. 
* Another thing if somebody just wants to send this backup_tags.txt to somewhere? or for statistics? or just showing to boss? He needs to open those 13 files manually combine them or running --show_tags and redirecting the output to another file, which is more tedious.

Does it make sense now?

**Comment by Komport** [comment]
You knows better muallim ;)

**Comment by ShahriyarR** [comment]
@Komport 
I have added the status column as well.
The result of PyTest run(not from cli):

```
$ cat backup_tags.txt
2017-11-07_16-17-58     Full    'My first full backup'  OK
2017-11-07_16-27-26     Inc     'My first inc backup'   OK
2017-11-07_16-28-37     Inc     'My second inc backup'  OK
```

**Comment by ShahriyarR** [comment]
From autoxtrabackup tool:
```
$ autoxtrabackup -v -lf /home/shahriyar.rzaev/autoxtrabackup2.log -l DEBUG --defaults_file=/home/shahriyar.rzaev/XB_TEST/server_dir/xb_2_3_ps_5_6.conf --backup --tag="This the full backup"
```

The result:
```
[shahriyar.rzaev@qaserver-02 ps_5_6_x_2_3]$ cat backup_tags.txt 
2017-11-07_16-42-42     Full    'This the full backup'  OK
```
Also debug message was added:
```
171107 16:44:23 completed OK!
2017-11-07 16:44:23 DEBUG    Adding backup tags
```

Second run for incremental backups:
```
$ autoxtrabackup -v -lf /home/shahriyar.rzaev/autoxtrabackup2.log -l DEBUG --defaults_file=/home/shahriyar.rzaev/XB_TEST/server_dir/xb_2_3_ps_5_6.conf --backup --tag="This the INC backup"
```

The result:
```
$ cat backup_tags.txt 
2017-11-07_16-42-42     Full    'This the full backup'  OK
2017-11-07_16-44-15     Inc     'This the INC backup'   OK
```

**Comment by ShahriyarR** [comment]
Changed the output a bit:

```
$ cat backup_tags.txt
2017-11-07_16-57-38     Full    OK      'This the Full backup'
2017-11-07_16-58-08     Inc     OK      'This INC backup'
```
