### ISSUE TITLE
Feature Request - Take another full backup if one already exists. 

### ISSUE THREAD

**Issue by Komport** [ShahriyarR/MySQL-AutoXtraBackup#177]
Hi. 
I did not find any way to take Full backup if one already exists. AutoXtraBackup automatically will detect Full backup and start taking Inc backup. What if I want 2 full backups in my backup_dir? As of now I have to move my current backups to different folder and start backup tool again. Can we add feature where I will chose which backup type I want? Like below
```
autoxtrabackup --backup=full
autoxtrabackup --backup=inc
autoxtrabackup --backup #normal behavior 
```

**Comment by ShahriyarR** [comment]
Hi,
The reason I choose this approach is, running backup script from crontab.
Say, I want to take backup every 2 hours every day:
`0 */2 * * * autoxtrabackup --backup`

It will take 1 full + increments every 2 hours. The next day i.e after 24 hours, the full backup will retire and will take new full backup + remove old full and increments and the cycle will start again.

What is the reason for another full backup in your request?

**Comment by Komport** [comment]
One reason could be to keep static backups. As of me this approach is not so flexible. What if my backup retention full backup every 12 hours?

**Comment by ShahriyarR** [comment]
Well it depends on policy of current user to give full backup retention and archive the backups.
In config you can give it as:

```
#Optional: set archive and rotation
#archive_dir=/home/shahriyar.rzaev/XB_TEST/backup_archives
#full_backup_interval=1 day
```

And it is parsed as:

```
            if 'full_backup_interval' in BCK:
                self.full_backup_interval = humanfriendly.parse_timespan(
                    BCK['full_backup_interval'])
            else:
                self.full_backup_interval = 86400
```

Could you please test it and give a feedback it it works properly here?

**Comment by Komport** [comment]
İ have missed this parameter. Now got it. Setting this parameter to full_backup_interval = 0 will take full backup whenever we want. 

There is a little BUT :) 
Each time we decide to do something out of our parameters (say take 2 full backups within a day - when our retention is 1 full in a day) we have to change our parameter file and after finishing backup change it back.
