### ISSUE TITLE
Archiving without tar but preparing

### ISSUE THREAD

**Issue by prox2k** [ShahriyarR/MySQL-AutoXtraBackup#246]
In environments with huge databases it would be great if I can change archiving settings to **not** to tar the archived backup (my backup needs 6hrs to tar, extracting that in disaster case would not be funny :)), just move it to the archive folder.

**Comment by ShahriyarR** [comment]
Hi,
Thanks for report.
How do you think? Is it okay, if I will implement the archiving like this?
* Define archive command in config file; such as `archive_cmd = /usr/bin/tar ....etc`
* If defined, run specified full command.
* If it is not defined, then move(mv) old backups(both full and incrementals) to specified archive directory.

**Comment by prox2k** [comment]
Hi,

I would suggest to Provide prepare the backups without tar. Maybe as you did suggest but with preparing optionally? archive_prepare=true or anything like that?

Merry Christmas!
Best
Sven

Am 21.12.2017 um 20:19 schrieb Shahriyar Rzayev <notifications@github.com<mailto:notifications@github.com>>:


Hi,
Thanks for report.
How do you think? Is it okay, if I will implement the archiving like this?

  *   Define archive command in config file; such as archive_cmd = /usr/bin/tar ....etc
  *   If defined, run specified full command.
  *   If it is not defined, then move(mv) old backups(both full and incrementals) to specified archive directory.

**Comment by ShahriyarR** [comment]
With this fix:
https://github.com/ShahriyarR/MySQL-AutoXtraBackup/issues/223

All backups are preparing prior archiving with 1.5.1 version of autoxtrabackup.

So basically, you want to choose:
* prepare + archive
or 
* just archive 

And also you want to have:
*  passing archiving command possibility
or
* just moving backups to archive directory

**Comment by ShahriyarR** [comment]
Implemented and merged to release_v1.5.2
Will be available on 1.5.2 version of autoxtrabackup.
Thanks for report.
