### ISSUE TITLE
Configurable log file rotation feature

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#254]
Got this feature request by email.
The logging file mechanism is handled as:

`file_handler = RotatingFileHandler(log_file, mode='a', maxBytes=104857600, backupCount=7)`

It would be greate to have `log_file_max_bytes` and `log_file_backup_count` options in config to increase, decrease even disable log file rotation

**Comment by ShahriyarR** [comment]
Changed the flow. It is better to have those options as commandline options

**Comment by JasperAlgra** [comment]
Hi @ShahriyarR,
As far I can see the `log_file_backup_count` argument rotates the appointed logfile to .log -> .log.1 -> log.2 etc per run?
And `log_file_max_bytes` does about the same but based on filesize?

Maybe this would be good to update in the option reference readme? http://mysql-autoxtrabackup.readthedocs.io/en/latest/option_reference.html
