### ISSUE TITLE
Some of my ideas:

### ISSUE THREAD

**Issue by Jiangnan-Ora-Xia** [ShahriyarR/MySQL-AutoXtraBackup#256]
1, backup to the remote, because you want to focus on management, to create a directory can be done in accordance with a certain logo? For example ip_prot/datetime
2, l remote backup system port, add a parameter to control it
3, the follow-up we want to integrate into the web using ansbile to tune or agent，related api it？
4, can add some api, can quickly add other backup features, such as mysqldump or tokudb or mydumper

**Comment by ShahriyarR** [comment]
Hi, to be honest  I did not understand the ideas in general.
Could you please share them more clearly and with examples?
Thanks.

**Comment by ShahriyarR** [comment]
Closing as there is no further actions on this.
