### ISSUE TITLE
Backup verification process - restoring backup to dummy mysql instance - "restore" mode

### ISSUE THREAD

**Issue by prox2k** [ShahriyarR/MySQL-AutoXtraBackup#258]
Hi Shahriyar,

to verify that made backups are working we restore them regularly.
It would be awesome to tell autoxtrabackup do that for us providing some configuration options like the remote. Than autoxtrabackup can push a specific backup to the remote and setup remote mysql configuration to get a working mysql instance with copied back backup.
Another option would be to give autoxtrabackup a "restore test" mode, which installs a temporary mysql instance and copy back and run a specific backup to it.

What do you think?

**Comment by ShahriyarR** [comment]
I have developed --test_mode of autoxtrabackup for testing xtrabackup itself.
http://mysql-autoxtrabackup.readthedocs.io/en/latest/test_mode.html

But your goal is slightly different and I think I can add this.
Basically you need:
* Take backup from your production db
* Prepare and verify it against new test MySQL.

I can implement it but there is some thing to think about - the new server must be started with same parameters as your prod db to be equal. We should figure out how to start exact clone of your running instance and to restore exactly to this new copy.

**Comment by ShahriyarR** [comment]
@prox2k any thoughts on this? ^^^

**Comment by ShahriyarR** [comment]
Closing as there is no attention on it anymore.
