### ISSUE TITLE
Make default config file as /tmp/bck.conf

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#282]
It requires sudo privilege to install default config file to /etc - which is not we want.

**Comment by JasperAlgra** [comment]
I could imagine overwriting or deleting /tmp dir altogether. What about /opt/ or another bit more persistent location?

**Comment by ShahriyarR** [comment]
Any location - with no need to sudo can be okay :)

**Comment by marmeladze** [comment]
Using environment variables might be another option. Or a profile file under `~/`

**Comment by ShahriyarR** [comment]
@marmeladze maybe you can send PR on this?

**Comment by ShahriyarR** [comment]
Maybe into `.autoxtrabackup` or maybe just `~/bck.conf`

**Comment by ziyaddin** [comment]
I see. Apart from changing all paths, constant path can be set (e.g. in "constants" file) and called in each file where bck.conf file path is required.

**Comment by ShahriyarR** [comment]
The main thing to change here is in:
https://github.com/ShahriyarR/MySQL-AutoXtraBackup/blob/master/setup.py#L3

Another thing is to look if somewhere, the default config path is used(hardcoded) or not.

**Comment by ziyaddin** [comment]
I will change all hardcoded ones to constant.

**Comment by ShahriyarR** [comment]
Fixed and merged as part of -> https://github.com/ShahriyarR/MySQL-AutoXtraBackup/issues/300
Thanks @ziyaddin for PR.
```
The default configuration is now stored in ~/.autoxtrabackup and renamed to autoxtrabackup.cnf
```
Closing this issue.
