### ISSUE TITLE
Multicore tar/gz zipping

### ISSUE THREAD

**Issue by JasperAlgra** [ShahriyarR/MySQL-AutoXtraBackup#284]
Hi @ShahriyarR,

First of all, many thanks for your great work! Really appreciating your wrap-around of the Percona tool. I'm in the process of automating our backups and this tool is already proving a time saver. 
That being said I've noticed a few things. I'll make separate issues and/or pull requests for them.

Would like like to offer multicore tar/zipping by use of pigz? In my case the time of compressing a database of +/- 800GB for archive takes more than half a day. This process is limited by the CPU of the tar process. By using pigz this time was approx cut in half.
https://stackoverflow.com/questions/12313242/utilizing-multi-core-for-targzip-bzip-compression-decompression

If you like this idea I could submit a pull request. Not too complicated: install pigz (apt-get or whatever) and change about two lines for the tar command. 

https://github.com/ShahriyarR/MySQL-AutoXtraBackup/blob/master/master_backup_script/backuper.py#L236
```
 # Multi-core tar utilizing pigz.
 # Pigz default to number of cores available, or 8 if cannot be read.
  run_tar = "tar cf - %s %s | pigz > %s" % (
  self.full_dir, self.inc_dir, self.archive_dir + '/' + i + '.tar.gz')
```

**Comment by ShahriyarR** [comment]
Hi @JasperAlgra 
Feel free to open issue for each your improvement(this one and future one) and create PRs based on them.
How about this?:
* check if pigz installed on our server.
* if yes then use it.
* if not then show the log message about missing pigz and tell user to install it. After message use default already existing solution.
