### ISSUE TITLE
Masking password in debug log

### ISSUE THREAD

**Issue by JasperAlgra** [ShahriyarR/MySQL-AutoXtraBackup#285]
For sharing of debug logs I would like to auto-mask the used passwords. I was on the verge of copy-pasting a debug log for another issue here on github when I noticed my backupuser's password being displayed plaintext.

If you thinks this is a good idea please let me know so I can create a pull request. It would be something like this: filtering out "--password='XYZ'" for the argument string just before logging to the debugger.

```
# filter out password from argument list
filteredargs = re.sub("--password='?\w+'?", "--password='*'", args)
logger.debug("The following backup command will be executed {}".format(filteredargs))
```

**Comment by ShahriyarR** [comment]
Hi @JasperAlgra,
Yes that is great idea. It will be great if you create PR for this.
Thanks.
