### ISSUE TITLE
Default mysql conf should be /etc/mysql/my.cnf

### ISSUE THREAD

**Issue by BarbzYHOOL** [ShahriyarR/MySQL-AutoXtraBackup#296]
I think in all installation /etc/mysql/my.cnf is present while /etc/my.cnf is not

**Comment by ShahriyarR** [comment]
Where you found this path?
Is it hard coded in code? Could you please clarify a bit?

**Comment by BarbzYHOOL** [comment]
oops, it's in /etc/bck.conf I think (I copied it from the docs, I couldn't find it nowhere in the repo)

    mycnf=/etc/my.cnf

**Comment by ShahriyarR** [comment]
This thing is related to MySQL itself.
So it needs to be edited after installation to reflect your path.

**Comment by BarbzYHOOL** [comment]
... yes but well i made a very small PR to illustrate what I mean, on some installation we don't have /etc/my.cnf so why using this one?? I bet every distribution has /etc/mysql/my.cnf
