### ISSUE TITLE
Questions about the config

### ISSUE THREAD

**Issue by BarbzYHOOL** [ShahriyarR/MySQL-AutoXtraBackup#297]
The documentation about the config is not very useful (sorry xD)

I have some questions because most of the conf options are "????????" to me

1)  What is this about:
#Optional: set pid directory
#pid_dir=/tmp/MySQL-AutoXtraBackup

2) max_archive_duration=1 day

By default it's "2 Days". Can we use "day" or "Day" or "DAY" or "DAYS" or "days"?

Do we need to put the "s" if more than 1 day?

I suggest to replace by "d" maybe?

3) This part is for you you said: [TestConf]

So you could put it in another configuration file that we don't look at :)

4) Wouldn't it be possible that autoxtrabackup takes the configuration of [mysqld] directly in the /etc/mysql directory? either my.cnf or inside the subdirs

5) the root password can be put in ~/my.cnf if I'm right, but it's not read by autoxtrabackup (minor issue)

6) the archives dir could be by default at the same level as "full" and "inc" (so we would have "full, inc, archives" in the same dir)

**Comment by ShahriyarR** [comment]
Too much questions :)
I think documentation will be quite improved in next release.
Because I got nice PRs related to DOCs.

**Comment by BarbzYHOOL** [comment]
what about 2)

**Comment by BarbzYHOOL** [comment]
7) what does max_archive_duration=1 day do?

8) Some variables lack consistent names "like one is `backupdir` and the other is `archive_dir`

**Comment by ShahriyarR** [comment]
11. Yes that is good suggestion. I am going to rename it to `autoxtrabackup.cnf`. Also there is  a PR:
https://github.com/ShahriyarR/MySQL-AutoXtraBackup/pull/294
Which is eliminating usage of global /etc path. New path will be something `~/.autoxtrabackup/`
So I am going to merge this change and after this will rename the config file name.

10. decompress=TRUE will decompress compressed backup while prior prepare stage :)

**Comment by ShahriyarR** [comment]
Also please see the updated version of DOC as it can contain answers for your questions:
https://github.com/ShahriyarR/MySQL-AutoXtraBackup/blob/release_v1.5.3/docs/config_file.rst

**Comment by BarbzYHOOL** [comment]
ok for decompress=True I discovered it by rereading xtrabackup docs but it was in that section "[Backup]" so that was a bit misleading, (would have put it into a [Restore] section instead)


Why this:
```

archive_dir
Directory for storing archives (tar.gz or otherwise). Cannot be inside the 'backupdir' above
```

I have put it exactly in my backupdir at the moment lol

And the doc is more useful now, thank you!!


I also suggest putting the conf in /etc/autoxtrabackup.d or something like that for multiple configs

**Comment by ShahriyarR** [comment]
Let me clarify a bit what we did recently.
So on release_v1.5.3 branch I have already changed the config file name to `autoxtrabackup.cnf` and now the default new place for log and config file is `~/.autoxtrabackup` folder.

With multiple configs I don't think that we need to force user to place it inside some directory. It is up to user. Also user can pass config file from any place using --defaults_file option in autoxtrabackup.

**Comment by BarbzYHOOL** [comment]
1) "With multiple configs I don't think that we need to force user to place it inside some directory" you don't force users, you just provide a classic way to store conf

or in /etc/autoxtrabackup/conf.d/

it's optional, if the dir doesn't exist then it's skipped

2) `--defaults_file` this could simply be changed to `--config / --conf / --configuration / -c`

3) So I can't put the archives directory inside the "backupdir"?? why?
