### ISSUE TITLE
1819 (HY000): Your password does not satisfy the current policy requirements

### ISSUE THREAD

**Issue by seru42000** [ShahriyarR/MySQL-AutoXtraBackup#3]
I have  a problem with running autoxtrabackup --backup option. it throws  an error indicating something related to password policy: 1819 (HY000): Your password does not satisfy the current policy requirements

-----------------------------------------
Here is full output:

    [root@ELSHAD_ThinkPad ~]# autoxtrabackup --backup
    Warning: Using a password on the command line interface can be insecure.
    Server is Up and running+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+OK
    /usr/bin/mysql exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-++-OK
    /usr/bin/mysqladmin exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
    MySQL configuration file exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+OK
    Xtrabackup/Innobackupex exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-OK
    Main backup directory does not exist+-+-+-+-+-+-+-+-+-++-+-+-+-
    Creating Main Backup folder+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+
    Created+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
    Full Backup directory does not exist.+-+-+-+-+-+-+-+-+-+-+-+-OK
    Creating full backup directory...+-+-+-+-+-+-+-+-+-++-+-+-+-+OK
    Created+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
    Increment directory does not exist.+-+-+-+-+-+-+-+-+-++-+-+-+OK
    Creating increment backup directory.+-+-+-+-+-+-+-+-+-++-+-+-OK
    Created
    Creating Test User (test_backup)+-+-+-+-+-+-+-+-+-++-+-+-+-+-OK
    1819 (HY000): Your password does not satisfy the current policy requirements
    Check status: STATUS+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-FAILED

**Comment by ShahriyarR** [comment]
Did you enable validate_password plugin or some other password policy plugin in MySQL?
Please run following command on your server:

    SHOW VARIABLES LIKE 'validate_password%';

**Comment by seru42000** [comment]
mysql> SHOW VARIABLES LIKE 'validate_password%';

+--------------------------------------+--------+
| Variable_name                        | Value  |
+--------------------------------------+--------+
| validate_password_dictionary_file    |        |
| validate_password_length             | 8      |
| validate_password_mixed_case_count   | 1      |
| validate_password_number_count       | 1      |
| validate_password_policy             | MEDIUM |
| validate_password_special_char_count | 1      |
+--------------------------------------+--------+
6 rows in set (0.00 sec)

**Comment by ShahriyarR** [comment]
Fixed as described:
-------------------------
When official validate_password plugin is active and there is a password policy in MySQL server, it will throw an error indicating that, password for creating test_backup use is not valid due to policy.
Added new User check functionality. it will check and generate random password related to policy.
Thank you for report.

**Comment by wangyouyan** [comment]
Actually,It's so easy to solve this issue.
firstly,we can use 'ps -ef |grep mysql' and get the below result:
ps -ef |grep mysql
    ->    74  1389     1   0  5:03下午 ??         0:00.27 /usr/local/mysql/bin/mysqld --user=_mysql --basedir=/usr/local/mysql --datadir=/usr/local/mysql/data --plugin-dir=/usr/local/mysql/lib/plugin --log-error=/usr/local/mysql/data/mysqld.local.err --pid-file=/usr/local/mysql/data/mysqld.local.pid --port=3307

Second,we entry the 'usr/local/mysql/lib/plugin',get some .so file as below:
adt_null.so			libpluginmecab.so		mypluglib.so			semisync_slave.so
debug				libtest_framework.so		mysql_no_login.so		validate_password.so
ha_example.so			libtest_services.so		rewrite_example.so		version_token.so
innodb_engine.so		libtest_services_threaded.so	rewriter.so
libmemcached.so			locking_service.so		semisync_master.so

finally,delete this file 'validate_password.so '
sudo rm -rf validate_password.so 

Don't fogot to restart the mysql service.

**Comment by ShahriyarR** [comment]
Issue was fixed as simple as possible -> if there is a user password policy, it will generate password related to this policy.
sudo rm -rf validate_password.so?
Did you mean that validate password plugin should be disabled for using AutoXtraBackup?
This kind of requirement is not acceptable because password policy maybe critical for some MySQL installations.
Also I must note that, the proper way to uninstall validate password plugin(and any other plugin) is running:
"uninstall plugin validate_password" + deleting my.cnf file entries + restarting MySQL.

**Comment by wangyouyan** [comment]
Hi ShahriyarR,The methods that I describled just fit the testing environment.

**Comment by xiaoshuai1127** [comment]
is there some command that i can used to disable the plugin or just modify the rules of this plugin?

**Comment by xiaoshuai1127** [comment]
u can find some solution in mysql manual:http://dev.mysql.com/doc/refman/5.6/en/validate-password-plugin.html#sysvar_validate_password_policy

**Comment by ShahriyarR** [comment]
As per comments indicate that users encountering several problems related to this issue.
Decided to disable completely 'test_backup' user creation process.
Will flush binary logs as root user. It will read global configuration file and perform log flushing under root user. That would be much more simple.
Thank you for attention.

**Comment by GlenCooper** [comment]
![Screenshot from 2021-03-07 01-27-57](https://user-images.githubusercontent.com/967793/110226122-66f66880-7ee4-11eb-92b7-855cb2b94cf2.png)
