### ISSUE TITLE
[Errno 13] Permission denied: '/var/log/autoxtrabackup.log' Please consider to run as root or sudo

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#302]
Eliminate the need of sudo for logging.

**Comment by ShahriyarR** [comment]
Fixed. Merged. Closing.

**Comment by BarbzYHOOL** [comment]
But don't we need sudo to backup databases anyway?

**Comment by ShahriyarR** [comment]
@BarbzYHOOL This issue was related to my test environment where I have changed all global locations to local.
For eg, in latest versions the default log and config files are in home folder inside .autoxtrabackup
```
shako@shako-localhost:~/.autoxtrabackup$ ls
autoxtrabackup.cnf  autoxtrabackup.log
```
