### ISSUE TITLE
Deleted database, but restore didn't restore it back

### ISSUE THREAD

**Issue by BarbzYHOOL** [ShahriyarR/MySQL-AutoXtraBackup#304]
Deb9

I tried to restore a backup, I deleted an entire database, and then I restored using autoxtrabackup --prepare

but the database has not been restored

What did I do wrong? Should I delete /var/lib/mysql manually first? Or does the script do it automatically for me?

**Comment by ShahriyarR** [comment]
Do you have log file?
Could you please share it or just paste here the entire output?

**Comment by BarbzYHOOL** [comment]
Ok, in fact it worked, I just had to log out and log back into my mysql client (like clear a cache)
