### ISSUE TITLE
logs of xtrabackup

### ISSUE THREAD

**Issue by ignaqui** [ShahriyarR/MySQL-AutoXtraBackup#307]
Hello,

I'm sorry if this question already being answered. I have searched in project's issues and found nothing relevant (overlooked?). Here is my question: how I can see xtrabackup's console output/logs, when autoxtrabackup invokes it?

Thank you

**Comment by ShahriyarR** [comment]
Hi,

```
Usage: autoxtrabackup [OPTIONS]

Options:
  --dry_run                       Enable the dry run.
  --prepare                       Prepare/recover backups.
  --backup                        Take full and incremental backups.
  --partial                       Recover specified table (partial recovery).
  --version                       Version information.
  --defaults_file TEXT            Read options from the given file  [default:
                                  /etc/bck.conf]
  --tag TEXT                      Pass the tag string for each backup
  --show_tags                     Show backup tags and exit
  -v, --verbose                   Be verbose (print to console)
  -lf, --log_file TEXT            Set log file  [default:
                                  /var/log/autoxtrabackup.log]
  -l, --log [DEBUG|INFO|WARNING|ERROR|CRITICAL]
                                  Set log level  [default: WARNING]
  --test_mode                     Enable test mode.Must be used with
                                  --defaults_file and only for TESTs for
                                  XtraBackup
  --help                          Print help message and exit.
```

You can append `-v -l DEBUG` to print output to console or you can specify the `-lf` (log file path) to be created and logged into this file.

**Comment by ignaqui** [comment]
Shahriyar,

Thank you for prompt response. And I'm sorry for not being clear in my previous post.

I already have options -v, -l DEBUG and -lf added into string. My concern is that I see logs from xtrabackup ONLY AFTER it completes all operations (perhaps logger dumps it do console and file upon xtrabackup's closure).
Meanwhile DURING the execution console and log file don't refresh. For example:
`2018-09-06 10:43:45 DEBUG    - - - - You have a full backup that is less than 1209600.0 seconds old. - - - -
2018-09-06 10:43:45 DEBUG    - - - - We will take an incremental one based on recent Full Backup - - - -
2018-09-06 10:43:48 DEBUG    The following backup command will be executed /usr/bin/xtrabackup --defaults-file=/etc/percona-xtradb-cluster.conf.d/mysqld.cnf --user=backup --password='XXXXX' --target-dir=/var/lib/mysql-backups/inc/2018-09-06_10-43-48 --incremental-basedir=/var/lib/mysql-backups/full/2018-09-05_16-32-21 --backup --socket=/var/lib/mysql/mysql.sock --compress=quicklz --compress-chunk-size=65536 --compress-threads=4 --no-version-check`

Is it possible to monitor logs DURING execution and not AFTER completion?

Cheers

**Comment by ShahriyarR** [comment]
@ignaqui 
Right, this is different thing to discuss.
So basically xtrabackup is an external command for us and I called it using `getstatusoutput`:

```
            logger.debug("Starting {}".format(self.backup_tool))
            status, output = subprocess.getstatusoutput(args)
            if status == 0:
                logger.debug(output)
                # truncated output
                return True
            else:
                logger.error("FAILED: FULL BACKUP")
                logger.error(output)
```

And from [DOC - getstatusoutput](https://docs.python.org/3/library/subprocess.html#subprocess.getstatusoutput) it is clear that it will return tuple of (status, output) after running the given command.

It is possible to make it print to stdout in realtime, as well as to the file.
Is it what you need? If you are able to summarize all your needs based on this, I can implement it.

**Comment by ignaqui** [comment]
@ShahriyarR 

I have pretty big database (ca. 7TBand growing), so it would be useful for me to be able monitor xtrabackup's logs in real time. If it's not too difficult to implement, that would be great.

Thank you

**Comment by ShahriyarR** [comment]
Okay I will see how to implement it.
It will be released soon I assume.

**Comment by prox2k** [comment]
This feature would help me, too!

**Comment by gitmstoute** [comment]
@ShahriyarR I started working on this :)

**Comment by ShahriyarR** [comment]
@gitmstoute Thank you very much :)
