### ISSUE TITLE
Error when using xtra_backup= Option

### ISSUE THREAD

**Issue by prox2k** [ShahriyarR/MySQL-AutoXtraBackup#325]
When using the xtra_backup= Option I get the following error:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/autoxtrabackup", line 11, in <module>
>     sys.exit(all_procedure())
>   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/autoxtrabackup.py", line 266, in all_procedure
>     b.all_backup()
>   File "/usr/local/lib/python3.5/dist-packages/master_backup_script/backuper.py", line 917, in all_backup
>     self.inc_backup()
>   File "/usr/local/lib/python3.5/dist-packages/master_backup_script/backuper.py", line 815, in inc_backup
>     logger.debug("The following backup command will be executed {}".format(filteredargs))
> UnboundLocalError: local variable 'filteredargs' referenced before assignment
> 

I tried to use the --rsync Option for xtrabackup to speedup the backup process.
xtra_backup=--rsync

**Comment by ShahriyarR** [comment]
Hi, It seems to be the same issue here:
https://github.com/ShahriyarR/MySQL-AutoXtraBackup/issues/318

It is already fixed in release_v1.5.4 branch.

**Comment by prox2k** [comment]
Hi, I'm sorry, I did not see the duplicate. Jep, fix works for me! Thank you!
