### ISSUE TITLE
--verbose doesn't show anything

### ISSUE THREAD

**Issue by BarbzYHOOL** [ShahriyarR/MySQL-AutoXtraBackup#326]
I'm on 1.5.2

If I use `autoxtrabackup -v -l DEBUG --backup ` it fills the console with information

But if I remove the -l DEBUG part there is nothing

If I change DEBUG to CRITIAL/INFO etc, there is nothing either !!!

**Comment by BarbzYHOOL** [comment]
ok but it's confusing :D maybe make it simpler until future implementation :P

**Comment by ShahriyarR** [comment]
:)) haha) just skip it. use -l DEBUG and that's it)

**Comment by BarbzYHOOL** [comment]
??? no `-l DEBUG` prints nothing to the console

Imo, there is a need to unify command names etc

**Comment by ShahriyarR** [comment]
Okay sorry, `-v -l DEBUG` )

**Comment by ShahriyarR** [comment]
I have changed the default log to `DEBUG` to make it clear that it will show necessary messages.

**Comment by BarbzYHOOL** [comment]
Ah yes, by removing `-v`

**Comment by gitmstoute** [comment]
It would be good to resolve this; with additional logging from #307, and only a single log-level, my autoxtrabackup logs are becoming relatively large (full backup is 15+mb log). I will try to work on it soon.

**Comment by ShahriyarR** [comment]
@gitmstoute Thanks.
