### ISSUE TITLE
Allow setting log file in the conf

### ISSUE THREAD

**Issue by BarbzYHOOL** [ShahriyarR/MySQL-AutoXtraBackup#327]
We should be able to set the log file directly in the conf :)

In fact most options should be in the conf (but overridable with command line switches)

**Comment by ShahriyarR** [comment]
Currently I don't remember what kind of thing should be there.
But will check. Thank you for report.

**Comment by ShahriyarR** [comment]
Valid report. But will be implemented in next releases.

**Comment by BarbzYHOOL** [comment]
I noticed this while making https://github.com/ShahriyarR/MySQL-AutoXtraBackup/issues/337

These options should be in the conf too (maybe overwritable by the command line, but it doesn't seem that useful):

```
--log (-l) --> --log-level --> -ll or no shortcut for this one (only 1 letter for shotcurts normally)
--log_file_backup_count -->  --log-file-backup-count
--log_file_max_bytes --> --log-file-max-bytes
```
