### ISSUE TITLE
error LANG UTF-8

### ISSUE THREAD

**Issue by BarbzYHOOL** [ShahriyarR/MySQL-AutoXtraBackup#328]
Any idea why I get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/autoxtrabackup", line 11, in <module>
    sys.exit(all_procedure())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/usr/local/lib/python3.6/dist-packages/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8

```

**Comment by ShahriyarR** [comment]
Again it seems to be an issue for `click` library. You can check if suggested environment variables fixes the issue.
Please do following exports and check again.

**Comment by BarbzYHOOL** [comment]
yeah but they fuck up everything else xD

I can change to en_US but still I had already configured my locales so it's kind of surprising it asks me for that

**Comment by ShahriyarR** [comment]
I did not find such issue with my environment.
So closing.

**Comment by BarbzYHOOL** [comment]
@ShahriyarR I have this issue again when running the script in a crontab, because cron doesn't have my environment variable set

Can't  you do something about it? lol I'm wondering if it's because I use LXC containers or if it's something that can be fixed in autoxtrabackup

And do you have this issue if you try to run autoxtrabackup in a crontab?

**Comment by ShahriyarR** [comment]
@BarbzYHOOL 

Well, even in official doc they have mentioned the problem:
https://click.palletsprojects.com/en/7.x/python3/#python-3-surrogate-handling

One of the questions:
https://stackoverflow.com/questions/32234393/encoding-issue-with-python3-and-click-package

You can specify this env variables in crontab as described here:
https://stackoverflow.com/questions/2229825/where-can-i-set-environment-variables-that-crontab-will-use

**Comment by BarbzYHOOL** [comment]
And do you have this issue if you try to run autoxtrabackup in a crontab?

**Comment by BarbzYHOOL** [comment]
add in cron.hourly/

```
#!/bin/sh

autoxtrabackup --backup
```

if you want to test

**Comment by ShahriyarR** [comment]
I know how to add things to crontab but still it is not an issue with `autoxtrabackup` it is related to `click` library which clearly described this issue and stated some workarounds.
Please figure out how to add env variables in cronjob.

**Comment by BarbzYHOOL** [comment]
ok so it means you would have this issue too and you don't use autoxtrabackup in a crontab?? weird I thought everybody would put it in cron

**Comment by ShahriyarR** [comment]
I have used as others and there was no issue like yours, until you have opened this issue.
So yes it means you will have such issue - you need to figure out how to pass env variables. That's it.
