### ISSUE TITLE
If permission error, then can't backup anymore

### ISSUE THREAD

**Issue by BarbzYHOOL** [ShahriyarR/MySQL-AutoXtraBackup#329]
If there was a permission error (to write the backup)

then it will print:

```
RuntimeError: FAILED: INCREMENT BACKUP
2018-12-22 12:16:55 DEBUG    <pid.PidFile object at 0x7f73a15c5688> closing pidfile: /tmp/autoxtrabackup/pid/autoxtrabackup.pid

```

because the script created an empty directory and it's looking for that file xtrabackup_checkpoints
inc/2018-12-22_12-14-17//xtrabackup_checkpoints

**Comment by ShahriyarR** [comment]
@BarbzYHOOL If you failed to make full backup then it is normal to have such issue.
Because to make incremental backup Percona XtraBackup is looking for `xtrabackup_checkpoints` file.

**Comment by BarbzYHOOL** [comment]
ok maybe you could add a message in the debug to check for empty backups or automatically delete them?

**Comment by ShahriyarR** [comment]
Well, if full backup failed and you did not fixed the issue - it is in general failed backup.
After that If I will delete empty full backup directory `autoxtrabackup` will detect it and will try to make another full backup which will fail again isn't it? :)

**Comment by BarbzYHOOL** [comment]
>After that If I will delete empty full backup directory autoxtrabackup will detect it and will try to make another full backup which will fail again isn't it? :)

true :D

maybe debug msg with a hint?
