### ISSUE TITLE
How to run it as a user?

### ISSUE THREAD

**Issue by BarbzYHOOL** [ShahriyarR/MySQL-AutoXtraBackup#330]
I try to run it as a user but i keep getting file permission errors

```
InnoDB: Failed to create check sector file, errno:13 Please confirm O_DIRECT is supported and remove the file /var/lib/check_sector_size if it exists.
InnoDB: Operating system error number 13 in a file operation.
InnoDB: The error means mysqld does not have the access rights to the directory.
InnoDB: Error in opening ./ib_logfile0

```

@ShahriyarR

**Comment by BarbzYHOOL** [comment]
`/var/lib/mysql/ib_logfile0`

belongs to mysql group @ShahriyarR

**Comment by ShahriyarR** [comment]
@BarbzYHOOL Welcome back :)
So based on error it seems to be the Unix system permissions problem.
Please see following discussion - maybe it can be useful.
https://bugs.mysql.com/bug.php?id=84488

**Comment by BarbzYHOOL** [comment]
I mean, how do you proceed yourself??

I can change /var/lib/mysql to be owned by a "backup" user or even chmod 777, or maybe create a group "percona" and add users `mysql` and `xtrabackup` in it?

What is your way of doing this? do you run it as root? @ShahriyarR

**Comment by ShahriyarR** [comment]
If you have already spotted that this is exactly the user issue then you can try it to run as `sudo` at least.
From official doc:
https://www.percona.com/doc/percona-xtrabackup/LATEST/using_xtrabackup/privileges.html#permissions-and-privileges-needed
```
Once connected to the server, in order to perform a backup you will need READ, WRITE and EXECUTE permissions at a filesystem level in the server’s datadir.
```

**Comment by BarbzYHOOL** [comment]
Of course it works with sudo, but you made a PR https://github.com/ShahriyarR/MySQL-AutoXtraBackup/issues/302 about not needing sudo

So I suppose you know how to proceed to NOT use sudo or root for autoxtrabackup.

So, how do you proceed yourself??

What is your way of doing this? do you run it as root? or with sudo?

How should I proceed?
I can change /var/lib/mysql to be owned by a specific "backup" user or even chmod 777, or maybe create a group "percona" and add users "mysql" and "xtrabackup" in it?

**Comment by BarbzYHOOL** [comment]
Found this solution:

     runuser -s "/bin/sh"  mysql -c "autoxtrabackup --backup -v -l DEBUG"

**Comment by BarbzYHOOL** [comment]
what do you think @ShahriyarR  :P

**Comment by ShahriyarR** [comment]
I did not have such issue with my tests and production servers :)
What do you suggest to add to autoxtrabackup in term of this?

**Comment by BarbzYHOOL** [comment]
I think nothing needs to be added but to the documentation eventually but in fact it's something related to xtrabackup, I just asked you because you're cool :P

It's just about permissions and by the way you didn't tell me how you run autoxtrabackup (as root, as sudo, or as a simple user but in that case what are your permissions on /var/lib/mysql etc)

@ShahriyarR

**Comment by ShahriyarR** [comment]
@BarbzYHOOL ahah :)
Let me describe the `Percona XtraBackup` and `autoxtrabackup` itself.
Percona's tool is for hot-online physical backup for MySQL server.
autoxtrabackup is basically Python wrapper command line tool with bunch of bugs :)
MySQL server is owned by `mysql` system user and datadir is owned by `mysql` user as well so it should not be changed. XtraBackup itself may require root privileges if you are going to parse system files, if you are going to backup to some system folder etc.
In general most of us using Percona XtraBackup  under sudo or root -  so this not a problem and should not be avoided. Consider situation, you have disaster, you have prepared your full and incremental backups and now you need to recover:
* You are going to shutdown MySQL - wipe the datadir(`/var/lib/mysql`)
* You are copying back backup files
* You are changing owner of new copied files inside datadir to `mysql:mysql`.
* You are trying to start MySQL server

Al these kind of steps are going to be possible only with root privileges.

**Comment by BarbzYHOOL** [comment]
ok, I don't remember how autoxtrabackup work for restoring backups but I suppose I can still run it as mysql user lol

I got confused because in one of your PR you talked about sudo for logs, and I still don't understand what was the point if everything else requires sudo

**Comment by ShahriyarR** [comment]
@BarbzYHOOL it was a specific case where I was testing in one of our test servers without polluting system folders.
Mentioned steps are fully automated by autoxtrabackup but still they can be achieved manually as well.
So just ignore those user related things and please continue to dig into and to find bugs :)

**Comment by BarbzYHOOL** [comment]
ok, at least my method works even if it's NOT needed (but i wanted to do it properly, in case a bug erases all my /root :P)
