### ISSUE TITLE
Unified command names

### ISSUE THREAD

**Issue by BarbzYHOOL** [ShahriyarR/MySQL-AutoXtraBackup#337]
@ShahriyarR 

Following common names in every program (on Unix), it should be like this:
```
--log (-l) --> --log-level --> -ll or no shortcut for this one (only 1 letter for shotcurts normally)
--log_file --> --log-file or --log --> -lf or -l
--defaults_file --> --config --> -c
--dry_run --> --dry-run
--show_tags -->--show-tags
--test_mode --> --test
--keyring_vault --> --keyring-vault
--log_file_backup_count -->  --log-file-backup-count
--log_file_max_bytes --> --log-file-max-bytes
--help --> --help and -h
```

This would help for cleaner usage.

Also check the PR I had made for the config file, it was about exactly the same issue.

Need also to edit the documentation though but we can probably do it with sed quite easily

**Comment by ShahriyarR** [comment]
Valid report can be implemented in future releases.
Need to check how `click` module works with that.
