### ISSUE TITLE
[List] Small improvements to config file

### ISSUE THREAD

**Issue by BarbzYHOOL** [ShahriyarR/MySQL-AutoXtraBackup#340]
This issue can be seen as a list of small improvements that can be made to the config file, to make it more practical to use and easy to manipulate. Feel free to add to it by commenting or directly editing my issue (for repo members):

## RENAMING

**Variable names:**
- [ ] max_archive_size --> archive_max_size
- [ ] max_archive_duration --> archive_max_duration
- [ ] backupdir --> backup_dir
- [ ] tmpdir --> tmp_dir
- [ ] datadir --> data_dir

**Comments:**
- [ ] `#use either socket or port + host combination` --> `## Set either mysql_socket only, OR host + port. If both are set mysql_socket is used`

## STRUCTURING

- [ ] Maybe group all the optional variables together? (I personally did that for clarity)
- [ ] Move the `[TestConf]` part to another file? or do not even include it? Seems rather useless for normal folks like me

**Comment by ShahriyarR** [comment]
Okay I am going to close other issues such as:
#327 and #337 
Everything mentioned in those issues will be implemented as part of this fix.

**Comment by ShahriyarR** [comment]
`datadir` will remain as datadir not data_dir because it is MySQL side variable  and should stay as original:

```
mysql> select @@datadir;
+-----------------+
| @@datadir       |
+-----------------+
| /var/lib/mysql/ |
+-----------------+
1 row in set (0.00 sec)
```

**Comment by ShahriyarR** [comment]
@BarbzYHOOL I have implemented bunch of your proposals.
Could you please check them - the branch is `release_v1.5.4`

**Comment by ShahriyarR** [comment]
It seems to be I can freeze this and merge to master to release new version.
Thank you for your reports, ideas. The Open Source history will not forget you.
