### ISSUE TITLE
tar.gz files not cleaned from archive dir 

### ISSUE THREAD

**Issue by gitmstoute** [ShahriyarR/MySQL-AutoXtraBackup#345]
When running with archive_dir set & move_archive = 0, autoxtrabackup places tar.gz files in the archive_dir. The tar.gz files are not removed during cleanup, so the archive_max_duration and archive_max_size configs are effectively ignored.

I will send a PR soon.

**Comment by ShahriyarR** [comment]
Great.
Waiting for your PR.
Thanks.

**Comment by gitmstoute** [comment]
submitted PR #346

**Comment by BarbzYHOOL** [comment]
Trivial fact: you should keep the issue open until it's merged and in your PR add "Closes https://github.com/ShahriyarR/MySQL-AutoXtraBackup/issues/345" so it will close it automatically :)

**Comment by gitmstoute** [comment]
Thanks @BarbzYHOOL ! I actually thought I did something wrong; Is it possible to submit a PR with the same ID (345) so it's automatically linked to this issue? I thought I had effectively accidentally duplicated my own issue with my PR.

**Comment by gitmstoute** [comment]
> Thanks @BarbzYHOOL ! I actually thought I did something wrong; Is it possible to submit a PR with the same ID (345) so it's automatically linked to this issue? I thought I had effectively accidentally duplicated my own issue with my PR.

I did a bit more reading so I understand it better - however I'm not sure where exactly to put "closes 345".
