### ISSUE TITLE
Dockerize the tool with development/test environment

### ISSUE THREAD

**Issue by Arlington1985** [ShahriyarR/MySQL-AutoXtraBackup#355]
It will be nice if we would have ready mysql installed development environment as an image in DockerHub or a DockerFile. While researching I have found following image from docker hub: https://hub.docker.com/r/ackstorm/autoxtrabackup. 
Not sure what is that, but anyway better generate official one

**Comment by ShahriyarR** [comment]
I am not aware of this image.
But yes it is better to have official one.
