### ISSUE TITLE
--tables-exclude & --databases-exclude ??

### ISSUE THREAD

**Issue by BarbzYHOOL** [ShahriyarR/MySQL-AutoXtraBackup#364]
Is there a way to exclude databases and tables like here:

https://www.percona.com/doc/percona-xtrabackup/2.3/xtrabackup_bin/xbk_option_reference.html#cmdoption-xtrabackup-databases-exclude

https://www.percona.com/doc/percona-xtrabackup/2.3/xtrabackup_bin/xbk_option_reference.html#cmdoption-xtrabackup-tables-exclude

--tables-exclude=name

@ShahriyarR

**Comment by BarbzYHOOL** [comment]
Also would need the --tables and --databases options too (or better, in the config file)
@ShahriyarR

**Comment by ShahriyarR** [comment]
@BarbzYHOOL did not check these options.
But yes you can pass xtrabackup options using xtra_options=

**Comment by BarbzYHOOL** [comment]
ok I think that will be enough then

I close until I test
