### ISSUE TITLE
excuting getting error

### ISSUE THREAD

**Issue by bimith** [ShahriyarR/MySQL-AutoXtraBackup#371]
autoxtrabackup -v -lf /home/XB_TEST/backup_dir/xb.log \ -l DEBUG --defaults-file=/home/XB_TEST/server_dir/bck.conf --backup
Usage: autoxtrabackup [OPTIONS]

Error: Got unexpected extra arguments ( -l DEBUG)

kindly tell me where is the error i have checked cross i did not find any faults
please help me

**Comment by ShahriyarR** [comment]
Please pull the latest master branch and install it using a fresh install.
`python3 setup.py install` is a good way of doing.

`autoxtrabackup --backup -v -l DEBUG -lf /home/XB_TEST/backup_dir/xb.log --defaults-file=/home/XB_TEST/server_dir/bck.conf` this command should work.
