### ISSUE TITLE
Prepare for code review and refactoring for new release v2.0

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#372]
First of all, remove unneeded, redundant and crappy features :dancer:

**Comment by ShahriyarR** [comment]
The project survived WW2 and will survive WW3 - due to this, respect bro respect )))))))

**Comment by gitmstoute** [comment]
woot woot and it will help our backups survive ww3! exciting flurry of activity this morning!!

**Comment by ShahriyarR** [comment]
:D I love you guys )
You make me forcefully hack again this already defeated east front.
Now comrades please prepare to fix extra shitty bugs )))))))

**Comment by ShahriyarR** [comment]
I think it is enough for 2.0 release as I am getting bored with refactoring )
