### ISSUE TITLE
Restore successfull but finaly mysql getting crashed

### ISSUE THREAD

**Issue by bimith** [ShahriyarR/MySQL-AutoXtraBackup#376]
See i have choosed 2 option and recoverd all my tables.
but finally mysql getting crashed please help me here

its very urgent.

**Comment by bimith** [comment]
please any one suggest me

**Comment by bimith** [comment]
partial i have completed successfully
debug has done properly/
But prepare backups and copy back immediately  not done 
in that everything will complete but finally the mysql server will go
kindly help me for this at least 
Dear Shako kindly respond i remember there are 22 emails are there regarding this 
but each time i have improved alone. In this case am totaly gone . Kindly do the help

**Comment by bimith** [comment]
When python install am getting like this error
              -DHGTAG="\"`LC_ALL=C `\"" \
              -DHGBRANCH="\"`LC_ALL=C `\"" \
              -o Modules/getbuildinfo.o ./Modules/getbuildinfo.c
gcc -pthread -c -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes    -Werror=declaration-after-statement -fprofile-generate   -I. -I./Include    -DPy_BUILD_CORE -o Programs/_freeze_importlib.o Programs/_freeze_importlib.c
gcc -pthread  -fprofile-generate  -o Programs/_freeze_importlib Programs/_freeze_importlib.o Modules/getbuildinfo.o Parser/acceler.o Parser/grammar1.o Parser/listnode.o Parser/node.o Parser/parser.o Parser/bitset.o Parser/metagrammar.o Parser/firstsets.o Parser/grammar.o Parser/pgen.o Parser/myreadline.o Parser/parsetok.o Parser/tokenizer.o Objects/abstract.o Objects/accu.o Objects/boolobject.o Objects/bytes_methods.o Objects/bytearrayobject.o Objects/bytesobject.o Objects/cellobject.o Objects/classobject.o Objects/codeobject.o Objects/complexobject.o Objects/descrobject.o Objects/enumobject.o Objects/exceptions.o Objects/genobject.o Objects/fileobject.o Objects/floatobject.o Objects/frameobject.o Objects/funcobject.o Objects/iterobject.o Objects/listobject.o Objects/longobject.o Objects/dictobject.o Objects/odictobject.o Objects/memoryobject.o Objects/methodobject.o Objects/moduleobject.o Objects/namespaceobject.o Objects/object.o Objects/obmalloc.o Objects/capsule.o Objects/rangeobject.o Objects/setobject.o Objects/sliceobject.o Objects/structseq.o Objects/tupleobject.o Objects/typeobject.o Objects/unicodeobject.o Objects/unicodectype.o Objects/weakrefobject.o Python/_warnings.o Python/Python-ast.o Python/asdl.o Python/ast.o Python/bltinmodule.o Python/ceval.o Python/compile.o Python/codecs.o Python/dynamic_annotations.o Python/errors.o Python/frozenmain.o Python/future.o Python/getargs.o Python/getcompiler.o Python/getcopyright.o Python/getplatform.o Python/getversion.o Python/graminit.o Python/import.o Python/importdl.o Python/marshal.o Python/modsupport.o Python/mystrtoul.o Python/mysnprintf.o Python/peephole.o Python/pyarena.o Python/pyctype.o Python/pyfpe.o Python/pyhash.o Python/pylifecycle.o Python/pymath.o Python/pystate.o Python/pythonrun.o Python/pytime.o Python/random.o Python/structmember.o Python/symtable.o Python/sysmodule.o Python/traceback.o Python/getopt.o Python/pystrcmp.o Python/pystrtod.o Python/pystrhex.o Python/dtoa.o Python/formatter_unicode.o Python/fileutils.o Python/dynload_shlib.o   Python/thread.o Modules/config.o Modules/getpath.o Modules/main.o Modules/gcmodule.o  Modules/_threadmodule.o  Modules/signalmodule.o  Modules/posixmodule.o  Modules/errnomodule.o  Modules/pwdmodule.o  Modules/_sre.o  Modules/_codecsmodule.o  Modules/_weakref.o  Modules/_functoolsmodule.o  Modules/_operator.o  Modules/_collectionsmodule.o  Modules/itertoolsmodule.o  Modules/atexitmodule.o  Modules/_stat.o  Modules/timemodule.o  Modules/_localemodule.o  Modules/_iomodule.o Modules/iobase.o Modules/fileio.o Modules/bytesio.o Modules/bufferedio.o Modules/textio.o Modules/stringio.o  Modules/zipimport.o  Modules/faulthandler.o  Modules/_tracemalloc.o Modules/hashtable.o  Modules/symtablemodule.o  Modules/_ssl.o  Modules/zlibmodule.o  Modules/xxsubtype.o -lpthread -ldl  -lutil -lrt -L/usr/local/ssl/lib -lssl -lcrypto  -L/usr/local/lib -lz   -lm
/usr/bin/ld: cannot find -lssl
collect2: ld returned 1 exit status
make[2]: *** [Programs/_freeze_importlib] Error 1
make[2]: Leaving directory `/else/pythoninstall/Python-3.5.3'
make[1]: *** [build_all_generate_profile] Error 2
make[1]: Leaving directory `/else/pythoninstall/Python-3.5.3'
make: *** [profile-opt] Error 2
[root@JMF-UAT Python-3.5.3]# build_all_generate_profile
-bash: build_all_generate_profile: command not found

**Comment by gitmstoute** [comment]
@bimith 

> See i have choosed 2 option and recoverd all my tables. but finally mysql getting crashed please help me here

Check mysql logs to determine why it crashed

> /usr/bin/ld: cannot find -lssl

https://askubuntu.com/questions/876441/error-usr-bin-ld-cannot-find-lssl. But didn't you already install python?

> Dear Shako

Who is Shako?

**Comment by bimith** [comment]
he is shahariyar

**Comment by bimith** [comment]
Actually am checking on client testing mechine
all part of middile and end  complete from our test mechine.
when i am trying at first time i have got same issue
am using rhel7.5 not using ubantu. help me bro

**Comment by gitmstoute** [comment]
> finally mysql getting crashed please help me here

> When python install am getting like this error

Which of these are you trying to fix?
Did you check the mysql error logs? 
I'm not familiar with rhel but usually mysql logs are in /var/log/mysql
