### ISSUE TITLE
update pip package

### ISSUE THREAD

**Issue by JasperAlgra** [ShahriyarR/MySQL-AutoXtraBackup#380]
Hi @ShahriyarR ,

Could you update the pip package at https://pypi.org/project/mysql-autoxtrabackup/ when you have the time?
Current pip-package version is 1.5.4.

Cheers,

Jasper

**Comment by JasperAlgra** [comment]
Hi @ShahriyarR sorry to bother you about this. But it would help me verry much since I'd rather not git/build the autoxtrabackup tool on production hosts but rely on the PIP package. 
And 1.5.5. has a major fix (deleting the archives).

**Comment by ShahriyarR** [comment]
:) Oh man, sorry about this.
I will try to fix the issue today or tomorrow.

**Comment by JasperAlgra** [comment]
@ShahriyarR  no worries! thanks a lot :)

**Comment by ShahriyarR** [comment]
@JasperAlgra sorry for late action.
I have uploaded the 1.5.5 version to PyPi.
Please check it :)

**Comment by ShahriyarR** [comment]
Closing now.

**Comment by JasperAlgra** [comment]
Thanks a lot! 
Working as advertised. I'm still looking into #382 and #384, was bit busy with other stuff but i'll let you know when/if i have a PR.

**Comment by ShahriyarR** [comment]
Thanks :)
I am trying to make most of unit/functional tests available for new 2.0 release as it is a major version change -  I must prove that the version change is valuable :D
