### ISSUE TITLE
Installation stratagy

### ISSUE THREAD

**Issue by bimith** [ShahriyarR/MySQL-AutoXtraBackup#385]
Dear Shacko,

shall we install this software in one  mechine and db server is running on another server
in this condition shall we take the backup using this tool. is it possible?

kindly guide me and it possible then give me the suggestions what changes i need to make in config file

**Comment by ShahriyarR** [comment]
*Shako
Nope, you can not do physical backup remotely, all setup actions should be done locally.
In other words, you should use autoxtrabackup alongside MySQL withing the same server.
Currently, there is no such functionality.
