### ISSUE TITLE
remotely backup

### ISSUE THREAD

**Issue by bimith** [ShahriyarR/MySQL-AutoXtraBackup#387]
Sir,
here we have server 1(db server)
server 2(backup server)
we have configured the auto-xtrabackup on server2 and given all details inside the bcf.cnf file about the db server. then we have tried the backup command. now the error is coming like Server is not up
what is the real error or this is the way we cannot do the backup?

please advise us. This is the we can take the backup it will be very fine

**Comment by ShahriyarR** [comment]
Again, the remote backup is not possible due to Percona XtraBackup design.
You can first backup locally and then send the backup via scp or rsync.
Secondly, you can do a streaming backup but it is a bit tricky.
Closing issue.
