### ISSUE TITLE
The project without tests

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#388]
We need more tests as we have no tests :D :D :dancer:

**Comment by BarbzYHOOL** [comment]
you mean "testing"?

we need more people to use this good project first, then add a label "waiting to be tested" on PRs

**Comment by ShahriyarR** [comment]
:) We have only one person who is trying to **** us with opening issues and still, there is no PR
I think the project should be covered by tests and must be improved with best practices in order to get more attention.

**Comment by ShahriyarR** [comment]
The basic idea is now for me:
* Try official MySQL Docker container
* Install autoxtrabackup in this container 
* Then write unit tests to run inside this container :dancer:

**Comment by BarbzYHOOL** [comment]
ok automated tests?

i only know about travis, to verify if everything works at a basic level

**Comment by gitmstoute** [comment]
@ShahriyarR Do you have a test framework in mind? I'm not familiar with them either but wouldn't mind learning/contributing.

**Comment by ShahriyarR** [comment]
I am going to use `pytest` and `docker` container for running tests.
I have already started to prepare docker env and wrote some wrapper code on this here:
https://github.com/ShahriyarR/MySQL-AutoXtraBackup/tree/bugfix_issue388

The thing is we are missing unit tests and of course functional tests overall.
So what you can do is - pick backup or prepare code and start to write unit tests for methods.

**Comment by ShahriyarR** [comment]
Nearly all the most important changes are done. The procedure to add more tests much more simple now. 
As it can take a month to cover all the tests I am going to merge current changes to release_v2.0 branch and try to continue to other important missing things.

**Comment by ShahriyarR** [comment]
Merged. Now closing.
Will open separate issues for each missing test type:
Prepare, Restore, Backup etc.
