### ISSUE TITLE
while installng pip3 install mysql-autoxtrabackup on linux rhel 7.5

### ISSUE THREAD

**Issue by bimith** [ShahriyarR/MySQL-AutoXtraBackup#393]
pip3 install mysql-autoxtrabackup
Collecting mysql-autoxtrabackup
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fedafe6f390>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/mysql-autoxtrabackup/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fedafe6fd68>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/mysql-autoxtrabackup/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fedafe6f6a0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/mysql-autoxtrabackup/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fedafe6f780>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/mysql-autoxtrabackup/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fedafe6f710>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/mysql-autoxtrabackup/
  Could not find a version that satisfies the requirement mysql-autoxtrabackup (from versions: )
No matching distribution found for mysql-autoxtrabackup

please help meurgently

**Comment by ShahriyarR** [comment]
`Failed to establish a new connection: [Errno -2] Name or service not known',)` 
This is somehow related to your internet connection I assume.
Please check if you have decent connection on your server.
