### ISSUE TITLE
server is not having the internet we have tried to install latest version master-using with python3 setup.py install

### ISSUE THREAD

**Issue by bimith** [ShahriyarR/MySQL-AutoXtraBackup#395]
Installing autoxtrabackup script to /usr/local/bin

Installed /usr/local/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.5-py3.5.egg
Processing dependencies for mysql-autoxtrabackup==1.5.5
Searching for pytest
Reading https://pypi.python.org/simple/pytest/
Download error on https://pypi.python.org/simple/pytest/: [Errno -2] Name or service not known -- Some packages may not be found!
Couldn't find index page for 'pytest' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
No local packages or working download links found for pytest
error: Could not find suitable distribution for Requirement.parse('pytest')

**Comment by ShahriyarR** [comment]
Please do not open issues for each of your errors, you have already opened a bunch of issues that are just duplicates.
You should either install every python dependency packages locally manually or you should have an internet connection on your server in order to download and install packages.
