### ISSUE TITLE
Installing on debian

### ISSUE THREAD

**Issue by genti-t** [ShahriyarR/MySQL-AutoXtraBackup#8]
I'm trying to install on  debian(jessie)
The installation stops on:
```
Installed /usr/local/lib/python3.4/dist-packages/mysql_autoxtrabackup-1.0-py3.4.egg
Processing dependencies for mysql-autoxtrabackup==1.0
Searching for mysql-connector-python>=2.0.2
Reading https://pypi.python.org/simple/mysql-connector-python/
No local packages or download links found for mysql-connector-python>=2.0.2
error: Could not find suitable distribution for Requirement.parse('mysql-connector-python>=2.0.2')
```
I have already installed mysql-connector-python from :
https://dev.mysql.com/doc/connector-python/en/connector-python-installation-binary.html

Why is it trying ... 
Reading https://pypi.python.org/simple/mysql-connector-python/

instead of:
https://pypi.python.org/pypi/mysql-connector-python/2.0.2

Can someone help me with this ?

**Comment by ShahriyarR** [comment]
Fixed as described:
'mysql-connector-python' is an external package which in turn, can not be downloaded from pip.
So I have added a dependency link in setup.py file.
Please pull and check again.
